# Project: 考古題111
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o loto.o car.o
LINKOBJ  = main.o loto.o car.o
LIBS     = -L"C:/Users/戴育琪/Downloads/DevCppPortable/MinGW64/lib" -L"C:/Users/戴育琪/Downloads/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Users/戴育琪/Downloads/DevCppPortable/MinGW64/include" -I"C:/Users/戴育琪/Downloads/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/戴育琪/Downloads/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/戴育琪/Downloads/DevCppPortable/MinGW64/include" -I"C:/Users/戴育琪/Downloads/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/戴育琪/Downloads/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/戴育琪/Downloads/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = test111.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

loto.o: loto.cpp
	$(CPP) -c loto.cpp -o loto.o $(CXXFLAGS)

car.o: car.cpp
	$(CPP) -c car.cpp -o car.o $(CXXFLAGS)
